### PR TITLE
Added support for PTR lookups

### PR DESCRIPTION
**Pull request by mzpqnxow**
As requested

### CODE REVIEW

**Comment by jaytaylor** [comment]
Awesome!  Thank you @agreene5! Just testing it now..

**Comment by jaytaylor** [comment]
LGTM.

**Comment by jaytaylor** [comment]
Thanks again!

**Comment by jaytaylor** [comment]
Thanks again!

```
echo 216.58.194.206 | ./bulkdns
216.58.194.206 sfo03s01-in-f14.1e100.net.
```

**Comment by mzpqnxow** [comment]
I have to bubble burst though :/

Without a rewrite, it's currently MUCH slower than doing:

time (nmap -sL -T5 0.0.0.0/0 -oG out;grep ^Host: out|cut -d ' ' -f2 >
resolved)

Try it out, maybe I screwed up. Use a smaller CIDR block to test.

About 10x slower..

Maybe it can be optimized, I haven't looked much at the code and I'm not a
great golang coder

**Comment by jaytaylor** [comment]
@agreene5 It was a quick little project, definitely haven't benchmarked it compared to the nmap hack.  The original use-case was to be able to easily embed the binary in a python web-app so we could do parallelized bulk resolution.

Would gladly welcome any PR's to improve this!

**Comment by mzpqnxow** [comment]
It's a cool project, I do use it, so thanks for that. One other issue though that is by no means a blocker and more of an inconvenience is that it can't be statically linked with libunbound- libunbound MUST be on the box- whether it be locally in your ~or wherever if you don't own the box, or on the system if you do. I like having standalone go binaries, but I can't find a way to link this statically with libunbound.

Do you know how to do this? I read a ton of docs and posts from golang mailing lists but just couldn't get it to link libunbound in statically- despite tons of attempts using both the gcc go compiler + GNU linker and golang compiler + golang link tool.

**Comment by jaytaylor** [comment]
Interesting, yes I'm aware it works this way and would love to make it more portable somehow so we could provide downloadable releases.

Do you have any specific details on what's prevented it from getting linked for you?

**Pull request merged**
